# =====================================================
# OIL & GAS REAL-TIME EQUIPMENT MONITORING
# Apache Flume Agent
# =====================================================

a1.sources = source1
a1.channels = channel1
a1.sinks = sink1

# =====================================================
# SOURCE
# =====================================================

a1.sources.source1.type = exec

a1.sources.source1.shell = powershell.exe -NoProfile -Command

a1.sources.source1.command = Get-Content -Path 'C:/LAB_CODE/3rdsem/oilgas/sensor_stream.txt' -Wait

a1.sources.source1.channels = channel1

# =====================================================
# CHANNEL
# =====================================================

a1.channels.channel1.type = memory

a1.channels.channel1.capacity = 1000

a1.channels.channel1.transactionCapacity = 100

# =====================================================
# SINK
# =====================================================

a1.sinks.sink1.type = file_roll

a1.sinks.sink1.sink.directory = C:/LAB_CODE/3rdsem/oilgas/output

a1.sinks.sink1.sink.rollInterval = 30

a1.sinks.sink1.channel = channel1